/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Arial24.c                                             *
* Font:        Arial                                                 *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0021 - 007E                                  *
*                                                                    *
**********************************************************************
*/

#include "font.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0021[ 15] = { /* code 0021, EXCLAMATION MARK */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0022[  5] = { /* code 0022, QUOTATION MARK */
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0023[ 30] = { /* code 0023, NUMBER SIGN */
  ____XX__,_XX_____,
  ____XX__,_XX_____,
  ____XX__,XXX_____,
  ___XX___,XX______,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  ___XX___,XX______,
  __XX___X,X_______,
  __XX___X,X_______,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  __XX___X,X_______,
  _XXX__XX,________,
  _XX___XX,________,
  _XX___XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0024[ 36] = { /* code 0024, DOLLAR SIGN */
  ____X___,________,
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX_X_XX,X_______,
  XX__X__X,X_______,
  XX__X___,________,
  XXX_X___,________,
  _XXXXX__,________,
  ___XXXXX,________,
  ____X_XX,X_______,
  ____X__X,X_______,
  ____X__X,X_______,
  XX__X__X,X_______,
  XXX_X_XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________,
  ____X___,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0025[ 45] = { /* code 0025, PERCENT SIGN */
  __XXX___,____XX__,________,
  _XX_XX__,___XX___,________,
  XX___XX_,___XX___,________,
  XX___XX_,__XX____,________,
  XX___XX_,__XX____,________,
  XX___XX_,_XX_____,________,
  _XX_XX__,XX______,________,
  __XXX___,XX__XXX_,________,
  _______X,X__XX_XX,________,
  _______X,X_XX___X,X_______,
  ______XX,__XX___X,X_______,
  ______XX,__XX___X,X_______,
  _____XX_,__XX___X,X_______,
  ____XX__,___XX_XX,________,
  ____XX__,____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0026[ 30] = { /* code 0026, AMPERSAND */
  ____XXXX,________,
  ___XXXXX,X_______,
  __XX____,XX______,
  __XX____,XX______,
  __XX___X,X_______,
  ___XX_XX,________,
  ___XXXX_,________,
  __XXXXX_,________,
  _XX__XXX,__XX____,
  XX____XX,X_XX____,
  XX_____X,XXX_____,
  XX______,XX______,
  XXX____X,XXX_____,
  _XXXXXXX,X_XX____,
  __XXXXX_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0027[  5] = { /* code 0027, APOSTROPHE */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0028[ 19] = { /* code 0028, LEFT PARENTHESIS */
  ____X___,
  ___X____,
  __XX____,
  __X_____,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX_____,
  _XX_____,
  __X_____,
  __XX____,
  ___X____,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0029[ 19] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  _XX_____,
  __X_____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __X_____,
  _XX_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_002A[  6] = { /* code 002A, ASTERISK */
  ___XX___,
  ___XX___,
  XXXXXXXX,
  ___XX___,
  __XXXX__,
  _XX__XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_002B[ 20] = { /* code 002B, PLUS SIGN */
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_002C[  5] = { /* code 002C, COMMA */
  XX______,
  XX______,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_002F[ 15] = { /* code 002F, SOLIDUS */
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0030[ 30] = { /* code 0030, DIGIT ZERO */
  __XXXXX_,________,
  _XXXXXXX,X_______,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  _XXXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0031[ 15] = { /* code 0031, DIGIT ONE */
  ____XX__,
  ____XX__,
  __XXXX__,
  _XXXXX__,
  XX__XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0032[ 30] = { /* code 0032, DIGIT TWO */
  __XXXXXX,________,
  _XXXXXXX,X_______,
  XXX____X,XX______,
  XX______,XX______,
  ________,XX______,
  ________,XX______,
  _______X,X_______,
  _______X,X_______,
  ______XX,________,
  ____XXX_,________,
  ___XXX__,________,
  __XX____,________,
  _XX_____,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0033[ 30] = { /* code 0033, DIGIT THREE */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  _______X,X_______,
  ______XX,________,
  ____XXX_,________,
  ____XXXX,X_______,
  _______X,XX______,
  ________,XX______,
  ________,XX______,
  XX______,XX______,
  XXX____X,X_______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0034[ 30] = { /* code 0034, DIGIT FOUR */
  _______X,________,
  ______XX,________,
  _____XXX,________,
  ____XXXX,________,
  ___XX_XX,________,
  ___XX_XX,________,
  __XX__XX,________,
  _XX___XX,________,
  XX____XX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0035[ 30] = { /* code 0035, DIGIT FIVE */
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_XXXX,________,
  XXXXXXXX,X_______,
  XX_____X,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  XX______,XX______,
  XXX____X,X_______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0036[ 30] = { /* code 0036, DIGIT SIX */
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XX____X,XX______,
  _XX_____,XX______,
  XX______,________,
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX____X,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  __XXXXXX,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0037[ 30] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _______X,X_______,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __XX____,________,
  __XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0038[ 30] = { /* code 0038, DIGIT EIGHT */
  ___XXXX_,________,
  __XXXXXX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XXXXXX,________,
  __XXXXXX,________,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXX____X,XX______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0039[ 30] = { /* code 0039, DIGIT NINE */
  ___XXXX_,________,
  _XXXXXXX,________,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,XX______,
  _XXXXXXX,XX______,
  __XXXX__,XX______,
  ________,XX______,
  XX_____X,X_______,
  XXX____X,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_003A[ 11] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_003B[ 14] = { /* code 003B, SEMICOLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_003C[ 22] = { /* code 003C, LESS-THAN SIGN */
  ________,_X______,
  _______X,XX______,
  _____XXX,X_______,
  ___XXXX_,________,
  _XXX____,________,
  XX______,________,
  _XXX____,________,
  ___XXXX_,________,
  _____XXX,X_______,
  _______X,XX______,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_003D[ 14] = { /* code 003D, EQUALS SIGN */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_003E[ 22] = { /* code 003E, GREATER-THAN SIGN */
  X_______,________,
  XXX_____,________,
  _XXXX___,________,
  ___XXXX_,________,
  ______XX,X_______,
  ________,XX______,
  ______XX,X_______,
  ___XXXX_,________,
  _XXXX___,________,
  XXX_____,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_003F[ 30] = { /* code 003F, QUESTION MARK */
  __XXXXXX,________,
  _XXXXXXX,X_______,
  XXX____X,XX______,
  XX______,XX______,
  ________,XX______,
  _______X,X_______,
  ______XX,X_______,
  _____XXX,________,
  ____XXX_,________,
  ____XX__,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0040[ 57] = { /* code 0040, COMMERCIAL AT */
  _______X,XXXXXX__,________,
  ____XXXX,XXXXXXXX,________,
  ___XXXX_,_____XXX,X_______,
  __XXX___,_______X,XX______,
  __XX____,XXX__XX_,XX______,
  _XX___XX,XXXX_XX_,XXX_____,
  _XX__XXX,___XXX__,_XX_____,
  XX___XX_,____XX__,_XX_____,
  XX__XX__,____XX__,_XX_____,
  XX__XX__,____XX__,_XX_____,
  XX__XX__,____X___,XXX_____,
  XX__XX__,___XX___,XX______,
  XX__XXX_,__XXX__X,X_______,
  _XX__XXX,XXXXXXXX,________,
  _XXX__XX,XX_XXXX_,_XX_____,
  __XXX___,________,XX______,
  ___XXXX_,______XX,X_______,
  ____XXXX,XXXXXXXX,________,
  ______XX,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0041[ 30] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XXX,________,
  _____XXX,________,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ___XX___,XX______,
  ___XX___,XX______,
  ___XX___,XX______,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  XX______,___XX___,
  XX______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0042[ 30] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XX_____X,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XX______,XX______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0043[ 30] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  __XXX___,_XXX____,
  _XX_____,__XXX___,
  XXX_____,___XX___,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXX_____,___XX___,
  _XX_____,__XX____,
  _XXXX___,_XXX____,
  __XXXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0044[ 30] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXXX,________,
  XXXXXXXX,XX______,
  XX______,XXX_____,
  XX______,_XX_____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,_XX_____,
  XX______,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0045[ 30] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0046[ 30] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0047[ 30] = { /* code 0047, LATIN CAPITAL LETTER G */
  ____XXXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXX___,__XXX___,
  _XX_____,___XXX__,
  _XX_____,____X___,
  XX______,________,
  XX______,________,
  XX_____X,XXXXXX__,
  XX_____X,XXXXXX__,
  XX______,____XX__,
  _XX_____,____XX__,
  _XX_____,____XX__,
  __XXX___,__XXXX__,
  ___XXXXX,XXXXX___,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0048[ 30] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0049[ 15] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_004A[ 15] = { /* code 004A, LATIN CAPITAL LETTER J */
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_004B[ 30] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX______,XXX_____,
  XX_____X,XX______,
  XX____XX,X_______,
  XX___XXX,________,
  XX__XXX_,________,
  XX_XXX__,________,
  XX_XXX__,________,
  XXXXXX__,________,
  XXX_XXX_,________,
  XX___XXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,XX______,
  XX______,XXX_____,
  XX______,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_004C[ 30] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_004D[ 30] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_____,____XXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XX_X____,___X_XX_,
  XX_XX___,__XX_XX_,
  XX_XX___,__XX_XX_,
  XX__X___,__X__XX_,
  XX__XX__,_XX__XX_,
  XX__XX__,_XX__XX_,
  XX___X__,_X___XX_,
  XX___XX_,XX___XX_,
  XX___XX_,XX___XX_,
  XX____X_,X____XX_,
  XX____XX,X____XX_,
  XX____XX,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_004E[ 30] = { /* code 004E, LATIN CAPITAL LETTER N */
  XX______,__XX____,
  XXX_____,__XX____,
  XXXX____,__XX____,
  XXXX____,__XX____,
  XX_XX___,__XX____,
  XX__XX__,__XX____,
  XX__XX__,__XX____,
  XX___XX_,__XX____,
  XX____XX,__XX____,
  XX____XX,__XX____,
  XX_____X,X_XX____,
  XX______,XXXX____,
  XX______,XXXX____,
  XX______,_XXX____,
  XX______,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_004F[ 30] = { /* code 004F, LATIN CAPITAL LETTER O */
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  __XXX___,_XXX____,
  _XX_____,___XX___,
  XXX_____,___XXX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XXX_____,___XXX__,
  _XX_____,___XX___,
  __XXX___,_XXX____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0050[ 30] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  XX______,XXX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0051[ 32] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ____XXXX,XX______,
  ___XXXXX,XXXX____,
  __XXX___,_XXXX___,
  _XX_____,___XX___,
  XXX_____,___XXX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XXX_____,___XX___,
  _XX____X,XX_XX___,
  __XXX___,_XXX____,
  ___XXXXX,XXXXX___,
  ____XXXX,XX_XXX__,
  ________,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0052[ 30] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  XX______,XXX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______,
  XX____XX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,XX______,
  XX______,XXX_____,
  XX______,_XX_____,
  XX______,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0053[ 30] = { /* code 0053, LATIN CAPITAL LETTER S */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  _XXX____,_XXX____,
  _XX_____,__XX____,
  _XX_____,________,
  _XXX____,________,
  __XXXXXX,________,
  ____XXXX,XX______,
  ________,XXX_____,
  ________,__XX____,
  XX______,__XX____,
  XXX_____,__XX____,
  _XXX____,_XXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0054[ 30] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0055[ 30] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XXX____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0056[ 30] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,___XX___,
  XXX_____,__XXX___,
  _XX_____,__XX____,
  _XX_____,__XX____,
  _XXX____,_XXX____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XXX___,XXX_____,
  ___XX___,XX______,
  ___XX___,XX______,
  ___XXX_X,XX______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ____XXXX,X_______,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0057[ 45] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX______,_XXX____,___XX___,
  XX______,_XXX____,___XX___,
  _XX_____,XX_XX___,__XX____,
  _XX_____,XX_XX___,__XX____,
  _XX_____,XX_XX___,__XX____,
  _XXX____,XX__X___,_XXX____,
  __XX___X,X___XX__,_XX_____,
  __XX___X,X___XX__,_XX_____,
  __XX___X,X___XX__,_XX_____,
  ___XX_XX,_____XX_,XX______,
  ___XX_XX,_____XX_,XX______,
  ___XX_XX,_____XX_,XX______,
  ___XX_XX,_____XX_,XX______,
  ____XXX_,______XX,X_______,
  ____XXX_,______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0058[ 30] = { /* code 0058, LATIN CAPITAL LETTER X */
  _XXX____,__XXX___,
  __XXX___,_XXX____,
  ___XX___,_XX_____,
  ____XX__,XX______,
  ____XX__,XX______,
  _____XXX,X_______,
  ______XX,________,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XX_X,XX______,
  ___XXX__,XXX_____,
  ___XX___,_XX_____,
  __XX____,__XX____,
  _XXX____,__XXX___,
  XXX_____,___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0059[ 30] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXX_____,___XXX__,
  _XX_____,___XX___,
  __XX____,__XX____,
  __XXX___,_XXX____,
  ___XXX__,XXX_____,
  ____XX__,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_005A[ 30] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  ________,_XX_____,
  ________,XX______,
  _______X,X_______,
  _______X,X_______,
  ______XX,________,
  _____XX_,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  _XX_____,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_005B[ 19] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXX____,
  XXXX____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_005C[ 15] = { /* code 005C, REVERSE SOLIDUS */
  XX______,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ____XX__,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_005D[ 19] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXXX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_005E[  8] = { /* code 005E, CIRCUMFLEX ACCENT */
  ___XX___,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_005F[  4] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0060[  3] = { /* code 0060, GRAVE ACCENT */
  XX______,
  _XX_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0061[ 22] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXXX,________,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  _______X,X_______,
  ____XXXX,X_______,
  _XXXXXXX,X_______,
  XXXX___X,X_______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,X_______,
  _XXXXX__,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0062[ 30] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,________,
  XXXXXXXX,________,
  XX_XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0063[ 22] = { /* code 0063, LATIN SMALL LETTER C */
  ___XXXX_,________,
  _XXXXXXX,________,
  _XX___XX,X_______,
  XX_____X,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_____X,X_______,
  _XX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0064[ 30] = { /* code 0064, LATIN SMALL LETTER D */
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  _XX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0065[ 22] = { /* code 0065, LATIN SMALL LETTER E */
  ___XXXX_,________,
  _XXXXXXX,X_______,
  _XX____X,X_______,
  XX______,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XX______,________,
  XX______,________,
  _XX____X,XX______,
  _XXXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0066[ 15] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXXX_,
  __XXXXX_,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0067[ 30] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  _XX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0068[ 30] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0069[ 15] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_006A[ 19] = { /* code 006A, LATIN SMALL LETTER J */
  __XX____,
  __XX____,
  ________,
  ________,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_006B[ 30] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX____XX,X_______,
  XX___XXX,________,
  XX__XXX_,________,
  XX_XXX__,________,
  XXXXX___,________,
  XXXXXX__,________,
  XX__XX__,________,
  XX___XX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_006C[ 15] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_006D[ 22] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXXX_,_XXXX___,
  XXXXXXX_,XXXXXX__,
  XXX___XX,X___XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_006E[ 22] = { /* code 006E, LATIN SMALL LETTER N */
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_006F[ 22] = { /* code 006F, LATIN SMALL LETTER O */
  ___XXXX_,________,
  _XXXXXXX,X_______,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  _XXXXXXX,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0070[ 30] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,________,
  XXXXXXXX,________,
  XX_XXXX_,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0071[ 30] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  _XX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0072[ 11] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XXX__,
  XXXXXX__,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0073[ 22] = { /* code 0073, LATIN SMALL LETTER S */
  __XXXXX_,________,
  _XXXXXXX,________,
  XX_____X,X_______,
  XX______,________,
  XXXXX___,________,
  _XXXXXXX,________,
  _____XXX,X_______,
  _______X,X_______,
  XX_____X,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0074[ 15] = { /* code 0074, LATIN SMALL LETTER T */
  __X_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXXX___,
  XXXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXX___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0075[ 22] = { /* code 0075, LATIN SMALL LETTER U */
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0076[ 22] = { /* code 0076, LATIN SMALL LETTER V */
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,XX______,
  _XX_____,XX______,
  __XX___X,X_______,
  __XX___X,X_______,
  ___XX_XX,________,
  ___XX_XX,________,
  ____XXX_,________,
  ____XXX_,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0077[ 33] = { /* code 0077, LATIN SMALL LETTER W */
  _XX_____,X_____XX,________,
  _XX____X,XX____XX,________,
  __X____X,XX____X_,________,
  __XX___X,_X___XX_,________,
  __XX__XX,_XX__XX_,________,
  ___XX_XX,_XX_XX__,________,
  ___XX_XX,_XX_XX__,________,
  ____X_X_,__X_X___,________,
  ____XXX_,__XXX___,________,
  ____XXX_,__XXX___,________,
  _____XX_,__XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0078[ 22] = { /* code 0078, LATIN SMALL LETTER X */
  XXX____X,XX______,
  _XX____X,X_______,
  __XX__XX,________,
  __XX__XX,________,
  ___XXXX_,________,
  ____XX__,________,
  ___XXXX_,________,
  __XX__XX,________,
  __XX__XX,________,
  _XX____X,X_______,
  XXX____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_0079[ 30] = { /* code 0079, LATIN SMALL LETTER Y */
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XXX__XX,________,
  __XX__XX,________,
  __XX_XX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  XXXXX___,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_007A[ 22] = { /* code 007A, LATIN SMALL LETTER Z */
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ______XX,X_______,
  _____XXX,________,
  ____XXX_,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  XXX_____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_007B[ 19] = { /* code 007B, LEFT CURLY BRACKET */
  ___XXX__,
  __XXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XXX____,
  XXX_____,
  XXX_____,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XXXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_007C[ 20] = { /* code 007C, VERTICAL LINE */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_007D[ 19] = { /* code 007D, RIGHT CURLY BRACKET */
  XXX_____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XXX___,
  ___XXX__,
  ___XXX__,
  __XXX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontArial24_007E[  8] = { /* code 007E, TILDE */
  _XXX____,________,
  XXXXXX__,_X______,
  X___XXXX,XX______,
  ______XX,X_______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontArial24_CharInfo[94] = {
   {   2,  15,   2,   4,   6, acGUI_FontArial24_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   6,   5,   1,   4,   7, acGUI_FontArial24_0022 } /* code 0022, QUOTATION MARK */
  ,{  12,  15,   0,   4,  12, acGUI_FontArial24_0023 } /* code 0023, NUMBER SIGN */
  ,{   9,  18,   1,   3,  12, acGUI_FontArial24_0024 } /* code 0024, DOLLAR SIGN */
  ,{  17,  15,   1,   4,  19, acGUI_FontArial24_0025 } /* code 0025, PERCENT SIGN */
  ,{  13,  15,   1,   4,  14, acGUI_FontArial24_0026 } /* code 0026, AMPERSAND */
  ,{   2,   5,   1,   4,   4, acGUI_FontArial24_0027 } /* code 0027, APOSTROPHE */
  ,{   5,  19,   1,   4,   7, acGUI_FontArial24_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   5,  19,   1,   4,   7, acGUI_FontArial24_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   8,   6,   0,   4,   8, acGUI_FontArial24_002A } /* code 002A, ASTERISK */
  ,{  10,  10,   1,   7,  12, acGUI_FontArial24_002B } /* code 002B, PLUS SIGN */
  ,{   2,   5,   2,  17,   6, acGUI_FontArial24_002C } /* code 002C, COMMA */
  ,{   6,   2,   0,  12,   7, acGUI_FontArial24_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   2,  17,   6, acGUI_FontArial24_002E } /* code 002E, FULL STOP */
  ,{   6,  15,   0,   4,   6, acGUI_FontArial24_002F } /* code 002F, SOLIDUS */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_0030 } /* code 0030, DIGIT ZERO */
  ,{   6,  15,   2,   4,  12, acGUI_FontArial24_0031 } /* code 0031, DIGIT ONE */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_0032 } /* code 0032, DIGIT TWO */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_0034 } /* code 0034, DIGIT FOUR */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_0035 } /* code 0035, DIGIT FIVE */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_0036 } /* code 0036, DIGIT SIX */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_0037 } /* code 0037, DIGIT SEVEN */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_0038 } /* code 0038, DIGIT EIGHT */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_0039 } /* code 0039, DIGIT NINE */
  ,{   2,  11,   2,   8,   6, acGUI_FontArial24_003A } /* code 003A, COLON */
  ,{   2,  14,   2,   8,   6, acGUI_FontArial24_003B } /* code 003B, SEMICOLON */
  ,{  10,  11,   1,   6,  12, acGUI_FontArial24_003C } /* code 003C, LESS-THAN SIGN */
  ,{  10,   7,   1,   8,  12, acGUI_FontArial24_003D } /* code 003D, EQUALS SIGN */
  ,{  10,  11,   1,   6,  12, acGUI_FontArial24_003E } /* code 003E, GREATER-THAN SIGN */
  ,{  10,  15,   1,   4,  12, acGUI_FontArial24_003F } /* code 003F, QUESTION MARK */
  ,{  19,  19,   1,   4,  21, acGUI_FontArial24_0040 } /* code 0040, COMMERCIAL AT */
  ,{  13,  15,   0,   4,  13, acGUI_FontArial24_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  11,  15,   2,   4,  14, acGUI_FontArial24_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  13,  15,   1,   4,  15, acGUI_FontArial24_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  12,  15,   2,   4,  15, acGUI_FontArial24_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  11,  15,   2,   4,  14, acGUI_FontArial24_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  10,  15,   2,   4,  13, acGUI_FontArial24_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  14,  15,   1,   4,  16, acGUI_FontArial24_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  12,  15,   1,   4,  14, acGUI_FontArial24_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  15,   2,   4,   6, acGUI_FontArial24_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   8,  15,   1,   4,  11, acGUI_FontArial24_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  12,  15,   2,   4,  14, acGUI_FontArial24_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   9,  15,   2,   4,  12, acGUI_FontArial24_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  15,  15,   1,   4,  17, acGUI_FontArial24_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  12,  15,   1,   4,  14, acGUI_FontArial24_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  14,  15,   1,   4,  16, acGUI_FontArial24_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  11,  15,   2,   4,  14, acGUI_FontArial24_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  14,  16,   1,   4,  16, acGUI_FontArial24_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  12,  15,   2,   4,  15, acGUI_FontArial24_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  12,  15,   1,   4,  14, acGUI_FontArial24_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  12,  15,   0,   4,  12, acGUI_FontArial24_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  12,  15,   1,   4,  14, acGUI_FontArial24_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  13,  15,   0,   4,  13, acGUI_FontArial24_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  21,  15,   0,   4,  21, acGUI_FontArial24_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  14,  15,   0,   4,  14, acGUI_FontArial24_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  14,  15,   0,   4,  14, acGUI_FontArial24_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  12,  15,   0,   4,  13, acGUI_FontArial24_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   4,  19,   1,   4,   6, acGUI_FontArial24_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   6,  15,   0,   4,   6, acGUI_FontArial24_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   4,  19,   1,   4,   6, acGUI_FontArial24_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   8,   8,   0,   4,   8, acGUI_FontArial24_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{  12,   2,   0,  21,  12, acGUI_FontArial24_005F } /* code 005F, LOW LINE */
  ,{   3,   3,   1,   4,   7, acGUI_FontArial24_0060 } /* code 0060, GRAVE ACCENT */
  ,{  10,  11,   1,   8,  12, acGUI_FontArial24_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   9,  15,   1,   4,  11, acGUI_FontArial24_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   9,  11,   1,   8,  11, acGUI_FontArial24_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   9,  15,   1,   4,  11, acGUI_FontArial24_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{  10,  11,   1,   8,  12, acGUI_FontArial24_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   7,  15,   0,   4,   6, acGUI_FontArial24_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   9,  15,   1,   8,  11, acGUI_FontArial24_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   9,  15,   1,   4,  11, acGUI_FontArial24_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  15,   1,   4,   5, acGUI_FontArial24_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   4,  19,  -1,   4,   4, acGUI_FontArial24_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   9,  15,   1,   4,  10, acGUI_FontArial24_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  15,   1,   4,   4, acGUI_FontArial24_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  14,  11,   1,   8,  16, acGUI_FontArial24_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   9,  11,   1,   8,  11, acGUI_FontArial24_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  10,  11,   1,   8,  12, acGUI_FontArial24_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   9,  15,   1,   8,  11, acGUI_FontArial24_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   9,  15,   1,   8,  11, acGUI_FontArial24_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   6,  11,   1,   8,   7, acGUI_FontArial24_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   9,  11,   1,   8,  11, acGUI_FontArial24_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,  15,   0,   4,   6, acGUI_FontArial24_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   9,  11,   1,   8,  11, acGUI_FontArial24_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  11,  11,   0,   8,  11, acGUI_FontArial24_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  17,  11,  -1,   8,  15, acGUI_FontArial24_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  10,  11,   0,   8,  10, acGUI_FontArial24_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   9,  15,   1,   8,  11, acGUI_FontArial24_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   9,  11,   0,   8,   9, acGUI_FontArial24_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   6,  19,   0,   4,   7, acGUI_FontArial24_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   2,  20,   2,   4,   6, acGUI_FontArial24_007C } /* code 007C, VERTICAL LINE */
  ,{   6,  19,   1,   4,   7, acGUI_FontArial24_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{  10,   4,   1,  10,  12, acGUI_FontArial24_007E } /* code 007E, TILDE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial24_Prop1 = {
   0x0021 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontArial24_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontArial24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontArial24_Prop1}
  ,19 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

